version: "2.4"
services:
  server:
    container_name: bot
    build: 
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Seoul
    networks:
      - backend
  
networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
